// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NetchexCodeProject.Models;
using System;

namespace NetchexCodeProject.Migrations
{
    [DbContext(typeof(NetchexContext))]
    partial class NetchexContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NetchexCodeProject.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("BirthDate");

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("MiddleName");

                    b.Property<string>("SocialSecurityNumber");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("NetchexCodeProject.Models.EmployeePay", b =>
                {
                    b.Property<int>("Id")
						.ValueGeneratedOnAdd();

					b.Property<int>("EmployeeId");

                    b.Property<DateTime>("HireDate");

                    b.Property<decimal>("HourlyRate");

                    b.Property<bool>("IsSalary");

                    b.Property<int>("PayFrequencyId");

                    b.Property<decimal>("PayPeriodAmount");

                    b.Property<decimal>("Salary");

                    b.HasKey("Id");

                    b.ToTable("EmployeePay");
                });

            modelBuilder.Entity("NetchexCodeProject.Models.PayFrequency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.Property<int>("PayPeriodsPerYear");

                    b.HasKey("Id");

                    b.ToTable("PayFrequency");
                });

            modelBuilder.Entity("NetchexCodeProject.Models.EmployeePay", b =>
                {
                    b.HasOne("NetchexCodeProject.Models.Employee", "Employee")
                        .WithOne("EmployeePay")
                        .HasForeignKey("NetchexCodeProject.Models.EmployeePay", "Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("NetchexCodeProject.Models.PayFrequency", "PayFrequency")
                        .WithOne("EmployeePay")
                        .HasForeignKey("NetchexCodeProject.Models.EmployeePay", "Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
